config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:index, :new, :create]
  post 'cart/add_to_cart', to: 'cart#add_to_cart'
  post 'cart/clear_cart', to: 'cart#clear_cart'
  get 'cart/show', to: 'cart#show'
  get 'cart/count', to: 'cart#cart_count'
  resources :orders, only: [:index, :create, :destroy, :show]
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart
  attr_reader :items

  def initialize(items = [])
    @items = items
  end

  def add_product(product_id)
    unless @items.include?(product_id)
      @items << product_id
      true
    else
      false
    end
  end

  def remove_product(product_id)
    @items.delete(product_id)
  end

  def clear
    @items = []
  end

  def empty?
    @items.empty?
  end

  def total_items
    @items.size
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  validates :total, presence: true
  validate :at_least_one_order_item

  before_validation :calculate_total

  private

  def calculate_total
    self.total = order_items.sum { |item| item.product.price }
    # Rails.logger.info "Calculated total before validation: #{self.total}"
  end

  def at_least_one_order_item
    errors.add(:base, "Debe haber al menos un producto en la orden") if order_items.empty?
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :set_cart


  def add_to_cart
    if @cart.add_product(params[:product_id])
      save_cart
      render json: { count: @cart.total_items, added: true }
    else
      render json: { count: @cart.total_items, added: false }
    end
  end

  def show
    @cart_items = Product.find(@cart.items)
    render json: @cart_items
  end

  def clear_cart
    @cart.clear
    save_cart
    render json: { message: "El carrito se ha limpiado correctamente" }
  end

  def cart_count
    render json: { count: @cart.total_items }
  end

  private

  def set_cart
    cart_data = cookies[:cart_data] ? JSON.parse(cookies[:cart_data]) : []
    @cart = Cart.new(cart_data)
  end

  def save_cart
    cookies[:cart_data] = { value: JSON.generate(@cart.items), expires: 1.week.from_now }
  end

  def cart_cache_key
    "cart_#{session.id}"
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_cart, only: [:create]

  def index
    @orders = Order.includes(:products).all
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.new
    @cart.items.each do |product_id|
      @order.order_items.build(product_id: product_id)
    end
    Rails.logger.info "Order items before saving: #{@order.order_items.map(&:product_id)}"
    if @order.save
      Rails.logger.info "Order saved successfully with total: #{@order.total}"
      clear_cart
      render json: { id: @order.id, message: 'Order was successfully created.' }, status: :created
    else
      Rails.logger.error "Order save failed with errors: #{@order.errors.full_messages}"
      render json: { errors: @order.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path, notice: 'Order was successfully destroyed.'
  end

  private

  def clear_cart
    @cart.clear
    save_cart
  end

  def set_cart
    cart_data = cookies[:cart_data] ? JSON.parse(cookies[:cart_data]) : []
    @cart = Cart.new(cart_data)
  end

  def save_cart
    cookies[:cart_data] = { value: JSON.generate(@cart.items), expires: 1.week.from_now }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.page(params[:page]).per(12)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MercatelyChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <%= render 'shared/navbar' %>

    <main class="container mx-auto mt-22 px-5">
      <%= yield %>
    </main>

    <%= render 'shared/cart_modal' %>
  </body>
</html>

app/views/orders/index.html.erb
<!-- app/views/orders/index.html.erb -->
<div class="container mx-auto mt-8">
  <h1 class="text-3xl font-bold mb-6">Órdenes</h1>

  <% if notice %>
    <div class="bg-green-100 border-t border-b border-green-500 text-green-700 px-4 py-3" role="alert">
      <p class="font-bold">Success</p>
      <p class="text-sm"><%= notice %></p>
    </div>
  <% end %>

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mt-6">
    <% @orders.each do |order| %>
      <div class="block bg-white rounded-lg shadow-md p-6 mb-6 transition-transform transform hover:scale-105 flex flex-col justify-between">
        <div>
          <h2 class="text-xl font-semibold mb-2">Orden #<%= order.id %></h2>
          <p class="text-gray-500 mb-4">Total: <%= number_to_currency(order.total) %></p>
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-2 mb-4">
            <% order.products.each do |product| %>
              <div class="flex justify-between">
                <span><%= product.name %></span>
                <span><%= number_to_currency(product.price) %></span>
              </div>
            <% end %>
          </div>
        </div>
        <div class="mt-auto flex justify-start space-x-2">
          <%= link_to 'Ver Orden', order_path(order), class: 'block buttons-bg buttons-bg-standar text-white px-4 py-2 rounded mb-2 text-center' %>
          <%= button_to 'Borrar Orden', order_path(order), method: :delete, class: 'block buttons-bg buttons-bg-red text-white px-4 py-2 ml-2 rounded text-center' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container mx-auto mt-8">
  <h1 class="text-3xl font-bold mb-6">Detalles de la Orden</h1>
  <div class="bg-white rounded-lg shadow-md p-6 mb-6 max-w-2xl mx-auto">
    <h2 class="text-xl font-semibold mb-4">Orden #<%= @order.id %></h2>
    <div class="border-b border-gray-200 pb-4 mb-4">
      <h3 class="text-lg font-medium mb-2">Productos</h3>
      <ul>
        <% @order.products.each do |product| %>
          <li class="flex justify-between mb-2">
            <span><%= product.name %></span>
            <span><%= number_to_currency(product.price) %></span>
          </li>
        <% end %>
      </ul>
    </div>

    <div class="text-right">
      <div class="flex justify-between text-xl font-bold pt-2">
        <span>Total:</span>
        <span><%= number_to_currency(@order.total) %></span>
      </div>
    </div>
  </div>
</div>
<div class="mt-6">
  <%= link_to 'Volver a Órdenes', orders_path, class: 'buttons-bg buttons-bg-standar text-white px-4 py-2 rounded' %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, class: "contents") do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 buttons-bg buttons-bg-standar text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= product.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    <%= product.price %>
  </p>

</div>

app/views/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Show this product", @product, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/index.html.erb
<div class="flex justify-center">
  <div class="w-full max-w-6xl">
    <h1 class="text-3xl font-bold mb-6 text-center">Productos</h1>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <% @products.each do |product| %>
        <div class="product bg-white rounded-lg shadow-md p-6 flex flex-col justify-between" data-product-id="<%= product.id %>">
          <div>
            <h2 class="text-xl font-semibold mb-2"><%= product.name %></h2>
            <p class="text-gray-500 mb-4">Price: <%= number_to_currency(product.price) %></p>
          </div>
          <div class="mt-4">
            <button data-product-id="<%= product.id %>" class="add-to-cart buttons-bg buttons-bg-standar text-white px-4 py-2 rounded">Add to Cart</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= paginate @products %>

app/views/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @product %>

    <%= link_to "Edit this product", edit_product_path(@product), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this product", @product, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/shared/_cart_modal.html.erb
<div id="cart-modal" class="fixed inset-0 bg-gray-600 bg-opacity-50 hidden flex justify-center items-center">
    <div class="bg-white p-6 rounded-lg shadow-lg w-full max-w-lg relative">
        <h2 class="text-xl font-bold mb-4">Carrito</h2>
        <div id="cart-items" class="mb-4">
            <!-- Productos del carrito -->
        </div>
        <div class="flex justify-end space-x-4">
            <button id="clear-cart" class="buttons-bg buttons-bg-red text-white px-4 py-2 rounded">Borrar Carrito</button>
            <button id="checkout" class="buttons-bg buttons-bg-save text-white px-4 py-2 rounded">Crear Orden</button>
        </div>
        <button id="close-modal" class="absolute top-0 right-0 mt-2 mr-2 text-gray-700">
            &times;
        </button>
    </div>
</div>

app/views/shared/_navbar.html.erb
<!-- app/views/shared/_navbar.html.erb -->
<header class="bg-gray-800 text-white p-4">
    <div class="container mx-auto flex justify-between items-center">
        <h1 class="text-xl font-bold">
            <%= link_to 'Mercately Challenge', root_path, class: 'hover:text-gray-300' %>
        </h1>
        <nav>
            <ul class="flex space-x-4">
            <li>
                <%= link_to 'Home', root_path, class: 'hover:text-gray-300' %>
            </li>
            <li>
                <%= link_to 'Órdenes', orders_path, class: 'hover:text-gray-300' %>
            </li>
            <li>
                <button id="cart-button" class="relative">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 7M7 13h.6l4 8H7m0-8L5.4 7m0 0H3"></path>
                </svg>
                <span id="cart-count" class="absolute top-0 right-0 bg-red-600 text-white rounded-full px-2 text-xs">0</span>
                </button>
                <div id="notification-save-product" class="fixed transform -translate-x-1/2 bg-slate-700 text-white px-4 py-2 rounded shadow-md hidden">
                    Producto agregado al carrito.
                </div>

            </li>
            </ul>
        </nav>
    </div>
</header>